# Generated by Django 3.1.2 on 2020-10-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybermini_nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodes',
            name='token',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
