# Generated by Django 3.1.3 on 2020-11-06 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cybermini_nodes', '0002_auto_20201020_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='channel_name',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('key', models.CharField(max_length=4)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybermini_nodes.nodes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
