# Generated by Django 3.1.3 on 2020-11-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybermini_nodes', '0003_auto_20201106_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='time_zone',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
